variables:
  CIBW_BUILD: cp37-* cp38-* cp39-*
  CIBW_BEFORE_BUILD_LINUX: yum install -y geos-devel freetype-devel libpng-devel

resources:
  repositories:
  - repository: OpenAstronomy
    type: github
    endpoint: astropy
    name: OpenAstronomy/azure-pipelines-templates
    ref: master

trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - 'v*'

jobs:

- template: publish.yml@OpenAstronomy
  parameters:
    test_command: pytest -p no:warnings --pyargs reproject
    test_extras: test
    ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/v') }}:
      pypi_connection_name : 'pypi_endpoint'
    targets:
    - sdist
    - wheels_linux
    - wheels_macos
    - wheels_windows
