[build-system]
requires = ["setuptools",
            "setuptools_scm",
            "wheel",
            "extension-helpers",
            "oldest-supported-numpy",
            "cython==0.29.21"]
build-backend = 'setuptools.build_meta'

[tool.cibuildwheel]
skip = "cp36-* pp* *-musllinux*"

[tool.cibuildwheel.linux]
before-build = "yum install -y geos-devel freetype-devel libpng-devel"
