[build-system]
requires = ["setuptools",
            "setuptools_scm",
            "wheel",
            "extension-helpers",
            "oldest-supported-numpy",
            "cython==0.29.21"]
build-backend = 'setuptools.build_meta'

[tool.cibuildwheel]
skip = "cp36-* pp* *-musllinux* cp310-win32"

[tool.isort]
    extend_skip_glob = [
        "docs/*",
        "setup.py"]
    line_length = 100
    known_third_party = ["astropy"]
    known_first_party = ["reproject"]
    multi_line_output = 4
    group_by_package = true
    indented_import_headings = false
    length_sort_sections = ["future", "stdlib"]
