name: CI

on:
  schedule:
    # run every day at 4am UTC
    - cron: '0 4 * * *'
  push:
  pull_request:
  workflow_dispatch:

groups:
  actions:
    patterns:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  tests:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      envs: |
        - macos: py39-test-oldestdeps
        - macos: py310-test
        - macos: py311-test
        - macos: py312-test
        - linux: py39-test-oldestdeps
        - linux: py310-test
        - linux: py311-test
        - linux: py312-test
        - linux: py312-test-devdeps
        - windows: py39-test-oldestdeps
        - windows: py310-test
        - windows: py311-test
        - windows: py312-test
      libraries: |
        apt:
          - libopenblas-dev
      coverage: 'codecov'

  publish:
    needs: tests
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish.yml@v1
    with:
      test_extras: test
      test_command: pytest -p no:warnings --pyargs reproject
      targets: |
        - cp*-manylinux_x86_64
        - cp*-manylinux_aarch64
        - cp*-macosx_x86_64
        - cp*-macosx_arm64
        - cp*-win_amd64

      # Developer wheels (use Numpy dev to build)
      upload_to_anaconda: ${{ (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') }}
      anaconda_user: astropy
      anaconda_package: reproject
      anaconda_keep_n_latest: 10
      env: |
        CIBW_BEFORE_BUILD: '${{ ((github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request') && 'pip install --pre --extra-index-url https://pypi.anaconda.org/scientific-python-nightly-wheels/simple setuptools setuptools_scm numpy>=0.0dev0 extension-helpers cython') || '' }}'
        CIBW_BUILD_FRONTEND: '${{ ((github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request') && 'pip; args: --no-build-isolation') || 'build' }}'

    secrets:
      pypi_token: ${{ secrets.pypi_token }}
      anaconda_token: ${{ secrets.anaconda_token }}
