name: CI

on:
  push:
  pull_request:

jobs:

  tests:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      envs: |
        - linux: codestyle
        - macos: py37-test-oldestdeps-cov
        - macos: py38-test-cov
        - macos: py39-test-cov
        - linux: py37-test-oldestdeps-cov
        - linux: py38-test-cov
        - linux: py39-test-cov
        - windows: py37-test-oldestdeps-cov
        - windows: py38-test-cov
        - windows: py39-test-cov
      coverage: 'codecov'

  publish:
    if: github.event_name != 'pull_request'
    needs: tests
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish.yml@v1
    with:
      test_extras: test
      test_command: pytest -p no:warnings --pyargs reproject
    secrets:
      pypi_token: ${{ secrets.pypi_token }}
