name: CI

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  tests:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      envs: |
        - linux: py311-test-devdeps
          python-version: '3.11.0-rc.2'
      libraries: |
        apt:
          - libopenblas-dev
      coverage: 'codecov'

  publish:
    needs: tests
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish.yml@v1
    with:
      test_extras: test
      test_command: pytest -p no:warnings --pyargs reproject
      targets: |
        - cp*-manylinux_x86_64
        - cp*-manylinux_aarch64
        - cp*-macosx_x86_64
        - cp*-macosx_arm64
        - cp*-win*
    secrets:
      pypi_token: ${{ secrets.pypi_token }}
