name: CI

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  tests:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      envs: |
        - linux: codestyle
        - macos: py38-test-oldestdeps
        - macos: py39-test
        - macos: py310-test
        - linux: py38-test-oldestdeps
        - linux: py38-test
        - linux: py39-test
        - linux: py310-test
        - windows: py38-test-oldestdeps
        - windows: py39-test
        - windows: py310-test
      coverage: 'codecov'

  publish:
    needs: tests
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish.yml@v1
    with:
      test_extras: test
      test_command: pytest -p no:warnings --pyargs reproject
    secrets:
      pypi_token: ${{ secrets.pypi_token }}
